### ISSUE TITLE
Getting 'InvalidParams'

### ISSUE THREAD

**Issue by feliwir** [picoHz/mediatype#20]
Hey,

thank you for this useful crate! I was switching from `mime` to this one, since i was unable to parse this content-type:
```
multipart/related; type="application/dicom"; boundary=2e7d39ff-37ea-4123-8604-53b2faee9847-a458cacb-2e98-41d0-9654-0803b18ca
```
However i also seem to error out with this crate. I get the `InvalidParam` result, but i don't see anything wrong. I get this content-type from a real DICOMweb server. Maybe the parser expects a trailing semicolon?

Could you please take a look? Thanks!

**Comment by picoHz** [comment]
@feliwir I've tested your example, and it can be parsed without error. 
I guess your input might contain some extra whitespace characters.
